name: CI-CD

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pipx install poetry

    - name: Install dependencies with Poetry
      run: poetry install --with dev

    - name: Build executable with PyInstaller
      run: |
        poetry run pyinstaller --onefile --name witd src/main.py

    - name: Rename executable
      run: |
        OS_NAME=${{ matrix.os }}
        EXT=""
        if [[ "$OS_NAME" == "windows-latest" ]]; then
          EXT=".exe"
        fi

        mv dist/main${EXT} dist/witd-${{ matrix.os }}${EXT}
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: witd-${{ matrix.os }}
        path: dist/
    
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: witd-*
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/**
          token: ${{ secrets.GH_PAT }}