name: CI-CD

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pipx install poetry

    - name: Install dependencies with Poetry
      run: poetry install --with dev

    - name: Build executable with PyInstaller
      run: |
        poetry run pyinstaller --onefile --name witd src/main.py

    - name: Rename executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mv dist/witd.exe dist/witd-windows.exe

    - name: Rename executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mv dist/witd dist/witd-linux

    - name: Rename executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        mv dist/witd dist/witd-macos

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: witd-${{ matrix.os }}
        path: dist/
    
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: witd-*
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/**
          token: ${{ secrets.GH_PAT }}